### ISSUE TITLE
About function declaration

### ISSUE THREAD

**Issue by CreeperLin** [ChenXinhao/ACM-Class-Compiler-2018#4]
Please specify the proper form of the return type and the parameter list in a function declaration, especially when returning an array type

**Comment by merrymercy** [comment]
```java
int [][] func(int[5][] a, string[] b, int n) {
    return new int[5][7];
}
```
Does this example make sense to you?

**Comment by CreeperLin** [comment]
Yes, thanks. But can parameters have initializers?

**Comment by merrymercy** [comment]
undefined behavior

**Comment by CreeperLin** [comment]
Okay, thanks.
